export const userRow = [
  {
    id: 1,
    gender: "Male",
    occupation: "FreeLancer",
    address: "Swiden",
    date: "12/01/2022",
    transaction: "$308.00",
    phone: "081673892038",
    firstname: "Donchi",
    lastname: "Ella",
    email: "donchi@gmail.com",
    status: "Active",
    img: "/ecoms/images/promo/macbook-new.jpg",
  },
  {
    id: 2,
    gender: "Female",
    occupation: "Lawyer",
    address: "New York",
    date: "12/01/2021",
    transaction: "$308.00",
    phone: "081673892038",
    lastname: "john",
    firstname: "Elvis",
    email: "elvis@gmail.com",
    status: "Active",
    img: "/ecoms/images/promo/macbook-new.jpg",
  },
  {
    id: 3,
    gender: "Male",
    occupation: "Farmer",
    address: "London",
    date: "12/08/2022",
    transaction: "$308.00",
    phone: "081673892038",
    lastname: "john",
    firstname: "Emmanual",
    email: "emmanuel@gmail.com",
    status: "Active",
    img: "/ecoms/images/promo/macbook-new.jpg",
  },
  {
    id: 4,
    gender: "Female",
    occupation: "Trader",
    address: "Las Vegas ",
    date: "12/06/2022",
    transaction: "$308.00",
    lastname: "john",
    firstname: "Chima",
    phone: "081673892038",
    email: "chima@gmail.com",
    status: "Active",
    img: "/ecoms/images/promo/macbook-new.jpg",
  },
  {
    id: 5,
    gender: "Male",
    occupation: "Accountant",
    address: "California",
    date: "12/01/2022",
    transaction: "$308.00",
    lastname: "john",
    firstname: "Chima",
    phone: "081673892038",
    email: "chima@gmail.com",
    status: "Active",
    img: "/ecoms/images/promo/macbook-new.jpg",
  },
  {
    id: 6,
    gender: "Female",
    occupation: "Teacher",
    address: "London Uk",
    date: "12/06/2022",
    transaction: "$308.00",
    lastname: "john",
    firstname: "Chima",
    phone: "081673892038",
    email: "chima@gmail.com",
    status: "Active",
    img: "/ecoms/images/promo/macbook-new.jpg",
  },
  {
    id: 7,
    gender: "Male",
    occupation: "Web developer",
    address: "New York",
    date: "12/01/2022",
    transaction: "$308.00",
    lastname: "john",
    firstname: "Chima",
    phone: "081673892038",
    email: "chima@gmail.com",
    status: "Active",
    img: "/ecoms/images/promo/macbook-new.jpg",
  },
  {
    id: 8,
    gender: "",
    occupation: "",
    address: "",
    date: "12/02/2021",
    transaction: "$308.00",
    lastname: "john",
    firstname: "Chima",
    phone: "081673892038",
    email: "chima@gmail.com",
    status: "Active",
    img: "/ecoms/images/promo/macbook-new.jpg",
  },
];
